#!/bin/bash -e

# first argument has to be the PBS script to run
# second argument has to be the number of times to repeat each job
# other arguments have to be config file paths (expected to end with .cfg)

# two arguments are passed to the PBS script: "cfg_file_name" and "repeat"

args=("$@")

repeat=1

for ((i=0; i < ${#args[*]}; i++)) do

	cfg_file_name=`echo ${args[i]} | sed 's|\(.*\)\.cfg$|\1|'`
	mkdir -p "${cfg_file_name}"

	for n in `seq 1 $repeat`; do

		SEED=$(( 10#`date +%N` % 900000000 ))

		python programs/simple_nve.py "${cfg_file_name}.cfg" "${cfg_file_name}" --seed $SEED --sim_length 100000 --MC_moves 0 --output_freq 10 --silent

		#python tools/cluster_analysis.py "${cfg_file_name}.cfg" "${cfg_file_name}/${SEED}.dump" --plot
	
	done
done
