#!/bin/bash -e

# Arguments passed to the script have to be config file paths (expected to end with .cfg)

args=("$@")

repeat=1

for ((i=0; i < ${#args[*]}; i++)) do

	cfg_file_name=`echo ${args[i]} | sed 's|\(.*\)\.cfg$|\1|'`
	mkdir -p "${cfg_file_name}"

	for n in `seq 1 $repeat`; do

		SEED=$(( 10#`date +%N` % 900000000 ))

		python programs/simple_nve.py "${cfg_file_name}.cfg" "${cfg_file_name}" --seed $SEED

		#python tools/cluster_analysis.py "${cfg_file_name}.cfg" "${cfg_file_name}/${SEED}.dump"
	
	done
done
