#!/bin/bash -e

# This script is for running multiple local simulations (and output processing) at a time

HOMEDIR="$(dirname "${BASH_SOURCE[0]}")"

program="$1"
simlen=100000
out_freq=1000

cfg_dir="$HOMEDIR/cfg_templates/5p_v3_out/"
run_dir="$HOMEDIR/run_templates/${program}_out/"

source ~/.python/venvs/lammps/bin/activate

for cfg_file in ${cfg_dir}*.cfg ; do
	
	cfg_filename="${cfg_file##*/}"
	cfg_filename="${cfg_filename%.cfg}"
	
	out_folder="$HOMEDIR/data/5p_v3/${cfg_filename}"
	
	for run_file in ${run_dir}*.run ; do

		run_filename="${run_file##*/}"
		run_filename="${run_filename%.run}"
		
		seed="$(date +"%T.%N")"
		seed=${seed##*.}
		seed=$(($seed % 1000000))
		
		mpiexec -n 2 python3 $HOMEDIR/programs/${program}.py "${cfg_file}" "${run_file}" ${simlen} --seed ${seed} --out "${out_folder}" -o ${out_freq}

		python3 $HOMEDIR/tools/dump_processing.py "${cfg_file}" "${out_folder}/${run_filename}_${seed}.dump" -c -l

	done
done

deactivate
