#!/bin/bash

#PBS -N <name>
#PBS -q batch

#PBS -l walltime=24:00:00
#PBS -l pmem=1G
#PBS -l nodes=1:ppn=1

#PBS -M eugen.rozic.17@ucl.ac.uk
#PBS -m aef

#PBS -o "${cfg_file_name}/${PBS_JOBID}.out"
#PBS -j oe

cd $PBS_O_WORKDIR # where qsub is called from

PROJECT_HOME="/storage/users/erozic/simulations/amyloids"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

SEED=$(( 10#${PBS_JOBID} % 900000000 ))

python "$PROJECT_HOME"/<script> "${cfg_file_name}.cfg" "${cfg_file_name}" $size $num $sim_len --seed $SEED <options>

dumpfile_name="${size}-${num}_${SEED}.dump"

python "$PROJECT_HOME"/tools/clusters/analysis.py "${cfg_file_name}.cfg" "${cfg_file_name}/${dumpfile_name}" <options>
