#!/bin/bash -l
#$ -S /bin/bash

#$ -N <name>

#$ -l h_rt=24:00:00
#$ -l mem=1G
#$ -l tmpfs=10M

#$ -M eugen.rozic.17@ucl.ac.uk
#$ -m ae

#$ -cwd

#$ -o "/home/ucapero/Scratch/job_outs/$JOB_ID.out"
#$ -j yes

PROJECT_HOME="/home/ucapero/simulations/amyloids"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

SEED=$(( 10#"${JOB_ID}" % 900000000 ))

python "$PROJECT_HOME"/<script> "${cfg_file_name}.cfg" "${cfg_file_name}" $size $num $sim_len --seed $SEED <options>

dumpfile_name="${size}-${num}_${SEED}.dump"

python "$PROJECT_HOME"/tools/clusters/analysis.py "${cfg_file_name}.cfg" "${cfg_file_name}/${dumpfile_name}" <options>
