#!/bin/bash

#PBS -N analysis
#PBS -q batch

#PBS -l walltime=<walltime>
#PBS -l pmem=<memory>
#PBS -l nodes=1:ppn=1

#PBS -o "<out_folder>/${PBS_JOBID}.out"
#PBS -j oe

cd $PBS_O_WORKDIR # where qsub is called from

PROJECT_HOME="<project_home>"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "WARNING: Virtualenv not found/activated! Using system python & LAMMPS..."
fi

python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" <aargs>
