#!/bin/bash

#PBS -N NAME
#PBS -q batch

#PBS -l walltime=<walltime>
#PBS -l pmem=<memory>
#PBS -l nodes=1:ppn=1

# PBS -M eugen.rozic.17@ucl.ac.uk
# PBS -m aef

#PBS -o "<out_folder>/${PBS_JOBID}.out"
#PBS -j oe

cd $PBS_O_WORKDIR # where qsub is called from

PROJECT_HOME="/storage/users/erozic/simulations/amyloids"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/../venv" ]; then
	source "$PROJECT_HOME"/../venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/../venv activated."
else
	echo "ERROR: Virtualenv not found/activated !!"
	exit
fi

SEED=$(( 10#${PBS_JOBID} % 900000000 ))

python "$PROJECT_HOME"/programs/SCRIPT "<cfg_file>" "<out_folder>" <cell_size> <num_cells> <sim_length> --seed $SEED FIXED_ARGS <args>

python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" "<out_folder>/<cell_size>-<num_cells>_${SEED}.dump" --every N
