#!/bin/bash

#PBS -N nucleation
#PBS -q batch

#PBS -l walltime=<walltime>
#PBS -l pmem=<memory>
#PBS -l nodes=1:ppn=<num_proc>

#PBS -o "<out_folder>/${PBS_JOBID}.out"
#PBS -j oe

cd $PBS_O_WORKDIR # where qsub is called from

PROJECT_HOME="<project_home>"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "WARNING: Virtualenv not found/activated! Using system python & LAMMPS..."
fi

JOB_ID=$( expr match "${PBS_JOBID}" '\([0-9]*\)' )
SEED=$(( 10#${JOB_ID} % 900000000 ))

/usr/bin/time --verbose mpiexec -f $PBS_NODEFILE python "$PROJECT_HOME"/programs/nucleation.py "<cfg_file>" "<run_file>" <simlen> --seed $SEED <args>

run_filename=`basename "<run_file>"`
run_filename="${run_filename%.*}"
python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" "<out_folder>/${run_filename}_${SEED}.dump" -c -l <aargs>
