#!/bin/bash -l
#$ -S /bin/bash

#$ -N analysis

#$ -l h_rt=<walltime>
#$ -l mem=<memory>
#$ -l tmpfs=0

#$ -M eugen.rozic.17@ucl.ac.uk
#$ -m ae

#$ -cwd

#$ -o "<out_folder>/$JOB_ID.out"
#$ -j yes

PROJECT_HOME="/home/ucapero/simulations/amyloids"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/../venv" ]; then
	source "$PROJECT_HOME"/../venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/../venv activated."
else
	echo "ERROR: Virtualenv not found/activated !!"
	exit
fi

python "$PROJECT_HOME"/tools/clusters/analysis.py "<cfg_file>" <out_folder>/*.dump <args>
