#!/bin/bash -l
#$ -S /bin/bash

#$ -N analysis

#$ -l h_rt=<walltime>
#$ -l mem=<memory>
#$ -l tmpfs=0

#$ -cwd

#$ -o "<out_folder>/$JOB_ID.out"
#$ -j yes

PROJECT_HOME="<project_home>"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "WARNING: Virtualenv not found/activated! Using system python & LAMMPS..."
fi

python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" <out_folder>/*.dump <args>
