#!/bin/bash -l
#$ -S /bin/bash

#$ -N membrane

#$ -l h_rt=<walltime>
#$ -l mem=<memory>
#$ -l tmpfs=0
#$ -pe mpi <num_proc>

#$ -cwd

#$ -o "<out_folder>/$JOB_ID.out"
#$ -j yes

PROJECT_HOME="<project_home>"

PYTHONPATH="$PROJECT_HOME/libs:$PYTHONPATH"
export PYTHONPATH

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "WARNING: Virtualenv not found/activated! Using system python & LAMMPS..."
fi

SEED=$(( 10#$JOB_ID % 900000000 ))

/usr/bin/time --verbose gerun python "$PROJECT_HOME"/programs/membrane.py "<cfg_file>" "<run_file>" <simlen> --seed $SEED <args>

run_filename=`basename "<run_file>"`
run_filename="${run_filename%.*}"
python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" "<out_folder>/${run_filename}_${SEED}.dump" -c -m --type_offset 3 <aargs>
