#!/bin/bash

#PBS -N analysis
#PBS -q cpu-single

#PBS -l ncpus=1
#PBS -l mem=<memory>
#PBS -l walltime=<walltime>

#PBS -M eugen.rozic.17@alumni.ucl.ac.uk
#PBS -m ae

#PBS -o "<out_folder>"
#PBS -j oe

export OMP_NUM_THREADS=1
[[ $PBS_JOBID =~ ([[:digit:]]+) ]] && JOB_ID="${BASH_REMATCH[1]}"

PROJECT_HOME="<project_home>"

cd $PBS_O_WORKDIR # where qsub is called from

module load cray-pals PrgEnv-cray

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "ERROR: Virtualenv not setup (no "venv" directory)! Aborting job..."
	exit
fi

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PROJECT_HOME}/venv/lib
py_version=$(python --version)
[[ $py_version =~ Python\ ([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+) ]] && py_version="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
export PYTHONPATH="${PYTHONPATH}:${PROJECT_HOME}/venv/lib/python${py_version}/site-packages"


python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" <aargs>
