#!/bin/bash

#PBS -N <name>
#PBS -q cpu

#PBS -l mpiprocs=<num_proc> ?
#PBS -l ncpus=<num_proc> ?
#PBS -l mem=<memory>
#PBS -l walltime=<walltime>

#PBS -M eugen.rozic.17@alumni.ucl.ac.uk
#PBS -m ae

#PBS -j oe

PROJECT_HOME="<project_home>"

JOB_ID=$( expr match "${PBS_JOBID}" '\([0-9]*\)' )

out_filename="${PBS_O_WORKDIR}/<name>.o${JOB_ID}"

cd $PBS_O_WORKDIR # where qsub is called from

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "WARNING: Virtualenv not found/activated! Using system python & LAMMPS..."
fi

SEED=$(( 10#${JOB_ID} % 900000000 ))

/usr/bin/time --verbose mpiexec -np <num_proc> python "$PROJECT_HOME"/programs/<script> "<cfg_file>" "<run_file>" <simlen> --seed $SEED <args>

run_filename=`basename "<run_file>"`
run_filename="${run_filename%.*}"
python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" "<out_folder>/${run_filename}_${SEED}.dump" <aargs>
