#!/bin/bash

#PBS -N <name>
#PBS -q cpu

#PBS -l ncpus=<num_proc>
#PBS -l mem=<memory>
#PBS -l walltime=<walltime>

<e_mail>#PBS -M <mail_address>
<e_mail>#PBS -m ae

#PBS -o "<out_folder>"
#PBS -j oe

export OMP_NUM_THREADS=1
[[ $PBS_JOBID =~ ([[:digit:]]+) ]] && JOB_ID="${BASH_REMATCH[1]}"

PROJECT_HOME="<project_home>"

cd $PBS_O_WORKDIR # where qsub is called from

module load cray-pals PrgEnv-cray

if [ -d "$PROJECT_HOME/venv" ]; then
	source "$PROJECT_HOME"/venv/bin/activate
	echo "Virtualenv at $PROJECT_HOME/venv activated."
else
	echo "ERROR: Virtualenv not setup (no "venv" directory)! Aborting job..."
	exit
fi

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PROJECT_HOME}/venv/lib
py_version=$(python --version)
[[ $py_version =~ Python\ ([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+) ]] && py_version="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
export PYTHONPATH="${PYTHONPATH}:${PROJECT_HOME}/venv/lib/python${py_version}/site-packages"

SEED=$(( 10#${JOB_ID} % 900000000 ))

/usr/bin/time --verbose mpiexec -np <num_proc> python "$PROJECT_HOME"/programs/<script> "<cfg_file>" "<run_file>" <simlen> --seed $SEED --out "<out_folder>" <args>

run_filename=`basename "<run_file>"`
run_filename="${run_filename%.*}"
python "$PROJECT_HOME"/tools/dump_processing.py "<cfg_file>" "<out_folder>/${run_filename}_${SEED}.dump" <aargs>
